version: '3.8'

services:
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"

  # Placeholder for your AuthService microservice
  auth_service:
    image: auth_service_image # Replace with the actual image name
    depends_on:
      - rabbitmq
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_DB_URI: ${MONGO_DB_URI}
    # ... other configurations

  # Placeholder for your UserService microservice
  user_service:
    image: user_service_image # Replace with the actual image name
    depends_on:
      - rabbitmq
    environment:
      MONGO_DB_URI: ${MONGO_DB_URI}